server:
  servlet:
    context-path: /api/v1
  port: 8081
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource}/${schema}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${dbUser}
    password: ${dbPwd}
    hikari:
      connection-timeout: 10000000
      validation-timeout: 10000000
      max-lifetime: 580000000
  redis:
    port: 6379
    host: ${datasource}
    password: ${redisPwd}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
  devtools:
    restart:
      enabled: false
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    allow-circular-references: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${rest_api_key}
            client-secret: ${client_secret_key}
            admin_key: ${admin_key}
            redirect-uri: https://j8b305.p.ssafy.io/api/v1/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

naver:
  shopping:
    client-id: ${clientId}
    client-secret: ${clientSecret}

jwt:
  header:
    access: Authorization
    refresh: RefreshToken
  type:
    access: "Bearer "
    refresh: "refresh-"
  time:
    access: 18000000
    refresh: 6048000000
  secret:
    key: ${jwt_secret_key}

user:
  url:
    fastapi: https://j8b305.p.ssafy.io/recom
    client: https://j8b305.p.ssafy.io
    logout: /api/v1/logout
    admin: /api/v1/admin
    member: /api/v1/member
    item: /api/v1/item
    recom: /api/v1/recom
    review: /api/v1/review
    likelist: /api/v1/likelist
    survey: /api/v1/survey
    test: /api/v1/test
    swagger: /api/v1/swagger-ui.html
    swagger-index: /api/v1/swagger-ui/
  role:
    admin: ROLE_ADMIN
    member: ROLE_MEMBER
  permit:
    all: '/**'
  session:
    id: 'JSESSIONID'
  cors:
    method: 'POST, GET, PUT, PATCH, DELETE'
    header: '*'
    pattern: '*'
    source:
      pattern: '/**'
  cookie:
    credential: true

logging:
  level:
    b305.coffeebrew.server: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
